<nav class="navbar navbar-expand-lg menu mb-5">
    <div class="container">
        <div class="navbar-nav">
            <a href="/timeline" class="menuItem">
                <i class="fa-solid fa-house"></i>
                Home
            </a>

            <a href="/sair" class="menuItem">
                <i class="fa-solid fa-power-off"></i>
                Sair
            </a>

            <a href="#" class="menuItem">
                <i class="fa-solid fa-user"></i>
                Perfil
            </a>

            <img src="/img/twitter_logo.png" alt="Logo" class="menuIco">
        </div>
    </div>
</nav>

<div class="container mt-5">

    <div class="row pt-2">

        <div class="col">
            <div class="perfilTopo">

            </div>

            <div class="perfilPainel">
                <div class="row mt-2 mb-2">
                    <div class="col mb-2">
                        <span class="perfilPainelNome">
                            Nome do usuarios
                        </span>
                    </div>
                </div>

                <div class="row mb-3 bordas">

                    <div class="col bordas">
                        <span class="perfilPainelItem">Tweets</span><br>
                        <span class="perfilPainelItemValor">
                            AAAAA
                        </span>
                    </div>

                    <div class="col bordas">
                        <span class="perfilPainelItem">Seguindo</span><br>
                        <span class="perfilPainelItemValor">
                            Seguidores
                        </span>
                    </div>

                    <div class="col bordas">
                        <span class="perfilPainelItem">Seguidores</span><br>
                        <span class="perfilPainelItemValor">
                            Seguindo
                        </span>
                    </div>

                </div>

                <div class="row mt-2 mb-2">
                    <div class="col mb-2">
                        <span class="perfilPainelNome">
                            Sobre mim
                        </span>
                    </div>
                </div>

                <div class="row mt-2">
                    <div class="col-md-6 ">
                        <div class="form-group shadow-textarea">
                            <textarea class="form-control z-depth-1" placeholder="Digite informações sobre a sua pessoa!" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-outline-info">Salvar</button>
                    </div>
                    <div class="col-md-6 ">
                        <div class="form-group">
                            <div class="row ml-2 mb-3">
                                <i class="fa-brands fa-instagram fa-lg mr-2"></i>
                                <input type="text" name="" id="">
                            </div>
                            <div class="row ml-2 mb-3">
                                <i class="fa-brands fa-facebook fa-lg mr-2"></i>
                                <input type="text" name="" id="">
                            </div>
                            <div class="row ml-2 mb-3">
                                <i class="fa-brands fa-linkedin fa-lg mr-2"></i>
                                <input type="text" name="" id="">
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>


</div>