<nav class="navbar navbar-expand-lg menu mb-5">
    <div class="container">
        <div class="navbar-nav">
            <a href="/timeline" class="menuItem">
                <i class="fa-solid fa-house"></i>
                Home
            </a>

            <a href="/perfil" class="menuItem">
                <i class="fa-solid fa-user"></i>
                Perfil
            </a>

            <a href="/sair" class="menuItem">
                <i class="fa-solid fa-power-off"></i>
                Sair
            </a>

            <img src="/img/twitter_logo.png" alt="Logo" class="menuIco">
        </div>
    </div>
</nav>

<div class="container mt-5">

    <div class="row pt-2">
        <div class="col">
            <div class="perfilTopoUsuario">

            </div>
        </div>
    </div>

    <div class="row pt-2">
        <div class="col-md-6">
            <div class="boxPadrao">
                <div class="perfilPainel">

                    <div class="row mt-2 mb-2">
                        <div class="col mb-2">
                            <span class="perfilPainelNome">
                                <?php echo $this->view->infoUsuario['nome'] ?>
                            </span>
                        </div>
                    </div>

                    <div class="row mb-2">

                        <div class="col">
                            <span class="perfilPainelItem">Tweets</span><br>
                            <span class="perfilPainelItemValor">
                                <?php echo $this->view->totalTweet['total_tweet'] ?>
                            </span>
                        </div>

                        <div class="col">
                            <span class="perfilPainelItem">Seguindo</span><br>
                            <span class="perfilPainelItemValor">
                                <?php echo $this->view->totalSeguindo['total_seguindo'] ?>
                            </span>
                        </div>

                        <div class="col">
                            <span class="perfilPainelItem">Seguidores</span><br>
                            <span class="perfilPainelItemValor">
                                <?php echo $this->view->totalSeguidores['total_seguidores'] ?>
                            </span>
                        </div>

                    </div>

                </div>
            </div>

            <div class="boxPadrao">
                <div class="perfilPainel">
                    <div class="row mt-2 mb-2">
                        <div class="col mb-2">
                            <span class="perfilPainelNome">
                                Biografia
                            </span>
                        </div>
                    </div>
                    <div class="row mt-2 mb-2">
                        <div class="col mb-2">
                            <form action="/biografia" method="post">
                                <textarea class="form-control mb-2" maxlength="195" name="biografia" id=""
                                    rows="3"><?php echo $this->view->infoUsuario['biografia'] ?> </textarea>
                                <span class="info">Total aceito de 195 caracteres</span>
                                <div class="col mt-2 d-flex justify-content-end">
                                    <button type="submit" class="btn btn-outline-primary">Salvar</button>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>

            <div class="boxPadrao">
                <div class="perfilPainel">
                    <div class="row mt-2 mb-2">
                        <div class="col mb-2">
                            <span class="perfilPainelNome">
                                Redes Sociais
                            </span>
                        </div>
                    </div>
                    <div class="row mt-2 mb-2">
                        <div class="col mb-2">
                            <form action="/redes_sociais" method="post">
                                <div class="form-group">
                                    <div class="d-flex align-items-center">
                                        <i class="fa-brands fa-facebook fa-lg" style="color: #3b5998;"></i>
                                        <input class="col-md-5 inputItem form-control" type="text" name="facebook"
                                            value="<?php echo $this->view->infoUsuario['facebook'] ?>"
                                            placeholder="Facebook">
                                        <i class="fa-brands fa-instagram fa-lg" style="color: #e1306c;"></i>
                                        <input class="col-md-5 inputItem form-control" type="text" name="instagram"
                                            value="<?php echo $this->view->infoUsuario['instagram'] ?>"
                                            placeholder="Instagram">
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <i class="fa-brands fa-linkedin fa-lg" style="color: #0e76a8;"></i>
                                        <input class="col-md-5 inputItem form-control" type="text" name="linkedin"
                                            value="<?php echo $this->view->infoUsuario['linkedin'] ?>"
                                            placeholder="Linkedin">
                                        <i class="fa-brands fa-tiktok fa-lg" style="color:  #000;"></i>
                                        <input class="col-md-5 inputItem form-control" type="text" name="tiktok"
                                            value="<?php echo $this->view->infoUsuario['tiktok'] ?>"
                                            placeholder="Tiktok">
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <i class="fa-solid fa-link fa-lg"></i>
                                        <input class="col-md-5 inputItem form-control" type="text" name="outros"
                                            value="<?php echo $this->view->infoUsuario['outros_links'] ?>"
                                            placeholder="Outros">
                                    </div>
                                </div>

                                <div class="col mt-2 d-flex justify-content-end">
                                    <button type="submit" class="btn btn-outline-primary">Salvar</button>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </div>

        <div class="col-md-6">

            <div class="row mb-2">
                <div class="col">
                    <div class="card boxPadrao">
                        <div class="card-body">
                            <form action="/seguindo" method="get">
                                <div class="input-group mb-3">
                                    <input type="text" name="pesquisarPor" class="form-control"
                                        placeholder="Quem você está procurando?">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="submit">Procurar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mb-2">
                <div class="col">

                    <?php foreach ($this->view->seguidores as $indece => $seguidor) { ?>

                    <div class="card boxPadrao">
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="col-md-6 perfilPainelNome">
                                    <?php echo $seguidor['seguidor'] ?>

                                </div>

                                <div class="col-md-6 d-flex justify-content-end">
                                    <div>
                                        <a href="/acao?acao=deixar_de_seguir_perfil&id_usuario=<?php echo $seguidor['id_usuario_seguindo'] ?>"
                                            class="btn btn-outline-danger">
                                            Deixar de seguir
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col perfilPainelItemBiografica">
                                    <?php echo nl2br($seguidor['biografia']) ?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <?php } ?>

                </div>
            </div>
        </div>

    </div>

</div>