<nav class="navbar navbar-expand-lg menu mb-5">
    <div class="container">
        <div class="navbar-nav">
            <a href="/timeline" class="menuItem">Home</a>
            <a href="/sair" class="menuItem">Sair</a>
            <img src="/img/twitter_logo.png" alt="Logo" class="menuIco">
        </div>
    </div>
</nav>

<div class="container mt-5">
    <div class="row pt-2">

        <div class="col-md-3">

            <div class="perfil">
                <div class="perfilTopo">

                </div>

                <div class="perfilPainel">

                    <div class="row mt-2 mb-2">
                        <div class="col mb-2">
                            <span class="perfilPainelNome">Nome do Usuário</span>
                        </div>
                    </div>

                    <div class="row mb-2">

                        <div class="col">
                            <span class="perfilPainelItem">Tweets</span><br>
                            <span class="perfilPainelItemValor">0</span>
                        </div>

                        <div class="col">
                            <span class="perfilPainelItem">Seguindo</span><br>
                            <span class="perfilPainelItemValor">0</span>
                        </div>

                        <div class="col">
                            <span class="perfilPainelItem">Seguidores</span><br>
                            <span class="perfilPainelItemValor">0</span>
                        </div>

                    </div>

                </div>
            </div>

        </div>

        <div class="col-md-6">
            <div class="row mb-2">
                <div class="col tweetBox">
                    <form action="/tweet" method="post">
                        <textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" rows="3"></textarea>
                        <div class="col mt-2 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Tweet</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row tweer">
                <div class="col">
                    <p><strong>Nome do Usuário</strong> <small class="text text-muted">-Data tweet-</small></p>
                    <p>Conteúdo do trem</p>
                    <br>

                    <form action="">
                        <div class="col d-flex justify-content-end">
                            <button type="submit" class="btn btn-outline-danger"><small>Remover</small></button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row tweer">
                <div class="col">
                    <p><strong>Nome do Usuário</strong> <small class="text text-muted">-Data tweet-</small></p>
                    <p>Conteúdo do trem</p>
                    <br>

                    <form action="">
                        <div class="col d-flex justify-content-end">
                            <button type="submit" class="btn btn-outline-danger"><small>Remover</small></button>
                        </div>
                    </form>
                </div>
            </div>

        </div>

        <div class="col-md-3">
            <div class="quemSeguir">
                <span class="quemSeguirTitulo">Quem Seguir</span>
                <br>
                <hr>
                <a href="#" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
            </div>
        </div>

    </div>
</div>