<nav class="navbar navbar-expand-lg menu mb-5">
    <div class="container">
        <div class="navbar-nav">
            <a href="/timeline" class="menuItem">
                <i class="fa-solid fa-house"></i>
                Home
            </a>

            <a href="/perfil" class="menuItem">
                <i class="fa-solid fa-user"></i>
                Perfil
            </a>

            <a href="/sair" class="menuItem">
                <i class="fa-solid fa-power-off"></i>
                Sair
            </a>

            <img src="/img/twitter_logo.png" alt="Logo" class="menuIco">
        </div>
    </div>
</nav>

<div class="container mt-5">
    <div class="row pt-2">

        <div class="col-md-3">

            <div class="boxPadrao">
                <div class="perfilTopo">

                </div>

                <div class="perfilPainel">

                    <div class="row mt-2 mb-2">
                        <div class="col mb-2">
                            <span class="perfilPainelNome">
                                <?php echo $this->view->infoUsuario['nome'] ?>
                            </span>
                        </div>
                    </div>

                    <div class="row mb-2">

                        <div class="col">
                            <span class="perfilPainelItem">Tweets</span><br>
                            <span class="perfilPainelItemValor">
                                <?php echo $this->view->totalTweet['total_tweet'] ?>
                            </span>
                        </div>

                        <div class="col">
                            <span class="perfilPainelItem">Seguindo</span><br>
                            <span class="perfilPainelItemValor">
                                <?php echo $this->view->totalSeguindo['total_seguindo'] ?>
                            </span>
                        </div>

                        <div class="col">
                            <span class="perfilPainelItem">Seguidores</span><br>
                            <span class="perfilPainelItemValor">
                                <?php echo $this->view->totalSeguidores['total_seguidores'] ?>
                            </span>
                        </div>

                    </div>

                </div>
            </div>

        </div>

        <div class="col-md-6">
            <div class="row mb-2">
                <div class="col tweetBox">
                    <form action="/tweet" method="post">
                        <textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" rows="3"></textarea>
                        <div class="col mt-2 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Tweet</button>
                        </div>
                    </form>
                </div>
            </div>
            <?php foreach ($this->view->tweets as $id_tweet => $tweet) { ?>
                <div class="row tweet">
                    <div class="col">
                        <p>
                            <strong>
                                <?php echo $tweet['nome'] ?>
                            </strong>

                            <small class="text text-muted">
                                <?php echo $tweet['data'] ?>
                            </small>
                        </p>

                        <p>
                            <?php echo $tweet['tweet'] ?>
                        </p>
                        <br>

                        <i class="fa-solid fa-heart mr-2 heart"></i>
                        <i class="fa-solid fa-comments comments"></i>

                        <?php if ($tweet['id_usuario'] == $_SESSION['id']) { ?>

                            <form action="/remove_tweet" method="post">
                                <div class="col d-flex justify-content-end">
                                    <input type="hidden" name="tweet" value="<?php echo $tweet['id'] ?>">
                                    <button type="submit" class="btn btn-outline-danger"><small>Remover</small></button>
                                </div>
                            </form>

                        <?php } ?>

                    </div>
                </div>
            <?php } ?>
        </div>

        <div class="col-md-3">
            <div class="quemSeguir">
                <span class="quemSeguirTitulo">Quem Seguir</span>
                <br>
                <hr>
                <a href="/quem_seguir" class="quemSeguirTxt">
                    <i class="fa-solid fa-magnifying-glass"></i>
                    Procurar por pessoas conhecidas
                </a>
            </div>
        </div>

    </div>
</div>